Repository openshift/autoheal, pull requests merged in 2018-04, with the labels that each got.

#24 Return error when awx requests fail
  pkg/awx/connection.go
Labels: size/S

#23 Return error if failed to obtain auth token
  pkg/awx/connection.go
Labels: size/XS

#20 Adjust manifests for new configuration mechanism
  README.md
  examples/new-friend-alert.json
  examples/node-down-alert.json
  manifests/autoheal-deployment.yml
  manifests/autoheal-role-binding.yml
  manifests/autoheal-role.yml
  manifests/autoheal-route.yml
  manifests/autoheal-service.yml
  manifests/awx-credentials-secret.yml
  manifests/awx-tls-secret.yml
  manifests/example-healing-rules.yml
  template.sh
  template.yml
Labels: size/XL

#31 Avoid `logging before flag.Parse`
  cmd/autoheal/main.go
Labels: size/XS

#27 Improve AWX request logging
  pkg/awx/connection.go
Labels: size/M

#26 Adjust to new tower auth mechanism
  pkg/awx/connection.go
  pkg/awx/internal/data/pat.go
Labels: size/M

#34 Secure connection by default between autoheal and AWX
  autoheal.yml
  cmd/autoheal/awx_job.go
  pkg/awx/connection.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/internal/data/config.go
Labels: size/M

#38 Document the `awx.insecure` parameter in `README.md`
  README.md
  autoheal.yml
Labels: size/S

#33 Expose a metric on launched AWX jobs
  cmd/autoheal/awx_job.go
  cmd/autoheal/healer.go
  cmd/autoheal/metrics_exporter.go
  cmd/autoheal/server.go
  documentation/metrics.md
Labels: size/M

#37 Add support for multiple configuration files
  cmd/autoheal/healer.go
  cmd/autoheal/server.go
  pkg/config/loader.go
Labels: size/M

#32 Healing action throttling
  README.md
  autoheal.yml
  cmd/autoheal/alerts_worker.go
  cmd/autoheal/healer.go
  cmd/autoheal/healer_test.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/internal/data/config.go
  pkg/memory/doc.go
  pkg/memory/short_term.go
  pkg/memory/short_term_test.go
Labels: size/XL

#46 Fix README.md
  README.md
Labels: size/XS

#50 Use `autoheal.openshift.io` API group
  cmd/autoheal/alerts_worker.go
  cmd/autoheal/awx_job.go
  cmd/autoheal/batch_job.go
  cmd/autoheal/healer_test.go
  cmd/autoheal/metrics_exporter.go
  cmd/autoheal/rule_change.go
  cmd/autoheal/rules_worker.go
  pkg/apis/autoheal/v1alpha2/doc.go
  pkg/apis/autoheal/v1alpha2/register.go
  pkg/apis/autoheal/v1alpha2/types.go
  pkg/apis/autoheal/v1alpha2/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/internal/data/config.go
  pkg/memory/short_term_test.go
  template.yml
Labels: size/L

#51 Start collection of AWX examples
  README.md
  examples/awx/README.md
  examples/awx/list_job_templates.go
  pkg/awx/connection.go
Labels: size/L

#49 Make secrets optional
  README.md
  autoheal.yml
  pkg/config/config.go
  pkg/config/loader.go
  pkg/internal/data/config.go
Labels: size/L

#55 Adding tests for config pkg
  pkg/config/loader_test.go
Labels: size/L

#58 Fix configuration loader tests
  pkg/config/loader_test.go
Labels: size/S

#61 Do not try to connect to openshift cluster on default
  Makefile
  README.md
  examples/autoheal-dev.yml
  hack/run-dev.sh
Labels: approved, lgtm, size/L

#63 Add a mock awx server for dev
  Makefile
  README.md
  examples/mock-awx/mock-awx.go
Labels: approved, lgtm, size/L

#62 Extract awx client
  Gopkg.lock
  Gopkg.toml
  cmd/autoheal/awx_job.go
  vendor/github.com/moolitayer/awx-client-go/awx/connection.go
  vendor/github.com/moolitayer/awx-client-go/awx/doc.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/authtoken.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/doc.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job_template.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job_template_launch.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job_templates.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/jobs.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/pat.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/project.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/projects.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/shared.go
  vendor/github.com/moolitayer/awx-client-go/awx/job.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_launch.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_launch_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_templates_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/jobs_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/list.go
  vendor/github.com/moolitayer/awx-client-go/awx/project.go
  vendor/github.com/moolitayer/awx-client-go/awx/project_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/projects_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/request.go
  vendor/github.com/moolitayer/awx-client-go/awx/resource.go
Labels: approved, lgtm, size/M

#52 Start collection of example playbooks
  examples/playbooks/README.md
  examples/playbooks/increase_ovirt_node_cpus.yml
  examples/playbooks/increase_ovirt_node_memory.yml
  examples/playbooks/start_ovirt_node.yml
Labels: approved, lgtm, size/L

#59 Add autoheal_actions_requested_total counter
  cmd/autoheal/alerts_worker.go
  cmd/autoheal/metrics_exporter.go
  documentation/metrics.md
Labels: approved, lgtm, size/M

#54 template: Deploy oauth-proxy sidecar for TLS + authentication
  README.md
  template.sh
  template.yml
Labels: approved, lgtm, size/L

#69 Add API type conversion
  cmd/autoheal/alerts_worker.go
  cmd/autoheal/awx_job.go
  cmd/autoheal/batch_job.go
  cmd/autoheal/healer_test.go
  cmd/autoheal/metrics_exporter.go
  cmd/autoheal/rule_change.go
  cmd/autoheal/rules_worker.go
  hack/update-codegen.sh
  pkg/apis/autoheal/register.go
  pkg/apis/autoheal/v1alpha2/doc.go
  pkg/apis/autoheal/v1alpha2/zz_generated.conversion.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/config/loader_test.go
  pkg/internal/data/config.go
Labels: approved, lgtm, size/L

#70 Expose metrics on job status
  cmd/autoheal/active_jobs_worker.go
  cmd/autoheal/awx_job.go
  cmd/autoheal/metrics_exporter.go
  documentation/metrics.md
Labels: approved, lgtm, size/M

#71 hack/test-go: Remove -i flag to allow running tests without root
  hack/test-go.sh
Labels: approved, lgtm, size/XS

#72 hack: Don't hardcode go version in verify_go_version
  hack/lib/util/golang.sh
Labels: approved, lgtm, size/XS

#75 Sync template with `openshift-ansible`
  template.sh
  template.yml
Labels: approved, lgtm, size/L

#67 Fix the way extraVars are sent to AWX.
  Gopkg.lock
  Gopkg.toml
  README.md
  autoheal.yml
  cmd/autoheal/object_template.go
  examples/autoheal-dev.yml
  examples/playbooks/increase_ovirt_node_cpus.yml
  examples/playbooks/increase_ovirt_node_memory.yml
  examples/playbooks/start_ovirt_node.yml
  pkg/apis/autoheal/types.go
  pkg/apis/autoheal/types_test.go
  pkg/apis/autoheal/v1alpha2/types.go
  pkg/apis/autoheal/v1alpha2/zz_generated.conversion.go
  pkg/apis/autoheal/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/autoheal/zz_generated.deepcopy.go
  pkg/memory/short_term_test.go
  vendor/github.com/moolitayer/awx-client-go/awx/job.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_launch_resource.go
Labels: approved, lgtm, size/L

#77 alertmanager/data: Add tests
  pkg/alertmanager/data_test.go
Labels: approved, lgtm, size/M

#76 Add alert content as an additional extra var to awx job
  README.md
  cmd/autoheal/awx_job.go
Labels: approved, lgtm, size/XS

#79 Update dev config file
  examples/autoheal-dev.yml
Labels: approved, lgtm, size/XS

#80 Add members of the team to the `OWNERS` file
  OWNERS
Labels: approved, lgtm, size/XS

#83 Add --logtostderr by default
  README.md
  cmd/autoheal/main.go
  hack/run-dev.sh
  template.yml
Labels: approved, lgtm, size/XS

#64 Watch config files for changes
  Gopkg.lock
  Gopkg.toml
  cmd/autoheal/healer.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/config/loader_test.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/yaacov/observer/LICENSE
  vendor/github.com/yaacov/observer/observer/observer.go
  vendor/github.com/yaacov/observer/observer/set/set.go
Labels: approved, lgtm, size/XXL

#92 Remove unused field
  pkg/batchrunner/batch_action_runner.go
Labels: approved, lgtm
