Repository openshift/autoheal, pull requests merged in 2018-05, with the labels that each got.

#88 object_template: Add tests
  cmd/autoheal/object_template_test.go
Labels: approved, lgtm, size/M

#90 Add support for passing the `limit` parameter to AWX jobs
  Gopkg.lock
  Gopkg.toml
  README.md
  autoheal.yml
  examples/autoheal-dev.yml
  pkg/apis/autoheal/types.go
  pkg/apis/autoheal/v1alpha2/types.go
  pkg/apis/autoheal/v1alpha2/zz_generated.conversion.go
  pkg/awxrunner/awx_action_runner.go
  vendor/github.com/moolitayer/awx-client-go/LICENSE.md
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job_template_launch.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_launch_resource.go
Labels: approved, lgtm, size/L

#95 Fix bug of templating a string field
  cmd/autoheal/object_template.go
  cmd/autoheal/object_template_test.go
Labels: approved, lgtm, size/M

#97 Buffer file change events
  pkg/config/event_listener.go
Labels: approved, lgtm, size/XS

#94 Adding tests for alert worker
  cmd/autoheal/alert_worker_test.go
  cmd/autoheal/healer_test.go
Labels: approved, lgtm, size/L

#96 Adding tests for rules worker
  cmd/autoheal/rules_worker_test.go
Labels: approved, lgtm, size/L

#98 Improve consistency of log messages
  cmd/autoheal/healer.go
  cmd/autoheal/object_template.go
  pkg/awxrunner/active_jobs_worker.go
  pkg/config/config.go
  pkg/config/event_listener.go
Labels: approved, lgtm, size/M

#99 Acquire mutex inside `Config.load`
  pkg/config/config.go
Labels: approved, lgtm, size/S

#100 Check config load errors
  pkg/config/builder.go
  pkg/config/config.go
Labels: approved, lgtm, size/S

#102 Upgrade observer version, watch for delete events
  Gopkg.lock
  Gopkg.toml
  pkg/config/builder.go
  pkg/config/config.go
  vendor/github.com/yaacov/observer/observer/observer.go
  vendor/github.com/yaacov/observer/observer/watch_event.go
Labels: approved, lgtm, size/L

#103 Check more errors when loading kubconfiig
  cmd/autoheal/server.go
  pkg/config/builder_test.go
Labels: approved, lgtm, size/L

#105 Check prompt-on-launch before launching a job
  Gopkg.lock
  Gopkg.toml
  pkg/awxrunner/awx_action_runner.go
  vendor/github.com/moolitayer/awx-client-go/awx/connection.go
  vendor/github.com/moolitayer/awx-client-go/awx/internal/data/job_template.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_template_resource.go
  vendor/github.com/moolitayer/awx-client-go/awx/job_templates_resource.go
Labels: approved, lgtm, size/L

#106 Example config: clarify what keys credentialsRef secret should have
  autoheal.yml
Labels: approved, lgtm, size/XS
