Repository openshift/autoheal, pull requests merged in 2018-03, with the labels that each got.

#1 Import from previous git
  .gitignore
  .travis.yml
  CHANGES.adoc
  Gopkg.lock
  Gopkg.toml
  LICENSE.txt
  Makefile
  README.adoc
  README.md
  boilerplate.go.txt
  build
  cmd/alert-healer/alerts_worker.go
  cmd/alert-healer/awx_job.go
  cmd/alert-healer/batch_job.go
  cmd/alert-healer/healer.go
  cmd/alert-healer/main.go
  cmd/alert-healer/object_template.go
  cmd/alert-healer/rule_change.go
  cmd/alert-healer/rules_worker.go
  images/alert-healer/Dockerfile.in
  manifests/awx-secret.yml
  manifests/crd-healing-rule.yml
  manifests/example-alert-message.json
  manifests/example-healing-rules.yml
  manifests/healer-deployment.yml
  manifests/healer-role-binding.yml
  manifests/healer-role.yml
  manifests/healer-route.yml
  manifests/healer-service-account.yml
  manifests/healer-service.yml
  pkg/alertmanager/data.go
  pkg/alertmanager/doc.go
  pkg/apis/monitoring/v1alpha1/doc.go
  pkg/apis/monitoring/v1alpha1/register.go
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/awx/connection.go
  pkg/awx/doc.go
  pkg/awx/internal/data/authtoken.go
  pkg/awx/internal/data/doc.go
  pkg/awx/internal/data/job_template.go
  pkg/awx/internal/data/job_template_launch.go
  pkg/awx/internal/data/job_templates.go
  pkg/awx/internal/data/shared.go
  pkg/awx/job_template.go
  pkg/awx/job_template_launch.go
  pkg/awx/job_template_launch_resource.go
  pkg/awx/job_template_resource.go
  pkg/awx/job_templates_resource.go
  pkg/awx/list.go
  pkg/awx/request.go
  pkg/awx/resource.go
  pkg/labels/doc.go
  pkg/labels/labels.go
  pkg/signals/signal.go
  playbooks/ensure_ovirt_node.yml
Labels: size/XXL

#3 Rename packages
  .travis.yml
  README.adoc
  build
  cmd/alert-healer/alerts_worker.go
  cmd/alert-healer/awx_job.go
  cmd/alert-healer/batch_job.go
  cmd/alert-healer/healer.go
  cmd/alert-healer/main.go
  cmd/alert-healer/rule_change.go
  cmd/alert-healer/rules_worker.go
  manifests/example-alert-message.json
  manifests/healer-deployment.yml
  manifests/healer-route.yml
  pkg/apis/monitoring/v1alpha1/doc.go
  pkg/awx/connection.go
  pkg/awx/job_template_launch_resource.go
  pkg/awx/job_template_resource.go
  pkg/awx/job_templates_resource.go
  playbooks/ensure_ovirt_node.yml
Labels: lgtm, size/M

#5 Compare Go versions numerically
  hack/lib/build/binaries.sh
Labels: size/XS

#17 Minor fixes in `README.md`
  README.md
Labels: size/XS

#19 Add alerts prefix to alerts endpoint
  README.md
  cmd/autoheal/healer.go
Labels: size/S

#21 Return a meaningful error for missing template
  cmd/autoheal/awx_job.go
Labels: size/XS
